# Copyright 2022 Chris Johns (chrisj@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

from __future__ import print_function

# Waf build script for an RTEMS Hello
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)
    bin_path = '${PREFIX}/' + \
        rtems.arch_bsp_path(bld.env.RTEMS_VERSION, bld.env.RTEMS_ARCH_BSP) + \
        '/bin'
    bsp = ['bspmain.c', 'debugger.c', 'network.c', 'init.c', 'dl.c']
    bld(features='c cxxprogram',
        target='xbutil',
        source=['xbutil.c'] + bsp,
        includes=['..',
                  '../include',
                  '../xrt/src/runtime_src/core/include',
                  '../xrt/src/runtime_src/core/edge/include'],
        cflags=['-O2', '-g'],
        use=['xrt'],
        lib=['debugger', 'bsd'],
        install_path=bin_path)
